name: "EA Hub Ingest Build & Test"

on:
  # Trigger on pull request creation or updates
  pull_request:
    paths:
      - "server/**" 
      - "tests/**"
  push:
    paths:
      - "server/**" 
      - "tests/**"

  
  workflow_dispatch:

jobs:
  # Job for pull request validation
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
        
      - name: Build image
        run: echo "POSTGRES_PASSWORD=sometestdbpassword" >> .env && docker compose build

      - name: Run tests
        run: docker compose up --exit-code-from ea-hub-ingest
